### PR TITLE
Add badges, fix some Go Report Card issues

### LINKED ISSUE #321: Add quality badges to the repository README
## Description

- Generate quality badges:
   - [Github Actions](https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge)
   - https://goreportcard.com/ 
   - https://bestpractices.coreinfrastructure.org/en
   - Consider Snyk and CodeClimate badges
- Check our score and fix detected issues

Timeboxed task, we do as much as we can in a given time.

## Reason

Show that we follow best practices during Capact development and that we do care about the quality of the project.

### PR DESCRIPTION
**Pull request by Trojan295**
## Description

Resolves #321

Changes proposed in this pull request:

- Add badges for:
  - license used
  - GitHub Action main branch build
  - Go Report Card
  - CII Best Practices
  - Snyk
- Resolve some Go Report Card comments

### CODE REVIEW

**Review by mszostok — COMMENTED** [review]
In general, it LGTM but is it a final version? It still reports a lot of golint issues.

**Comment by mszostok** [comment]
IMO we should remove for now the `CII Best Practices` and `CodeClimate` badges as we need to finish setup

File: cmd/cli/cmd/hub/implementations/get.go [hunk 1]
```diff
@@ -21,6 +21,7 @@ type getOptions struct {
 	implementationPaths []string
 }
 
+// NewGet returns a cobra.Command for getting Implementations from a public Hub.
```
Comment (Trojan295) [inline cmd/cli/cmd/hub/implementations/get.go:24]:
```suggestion
// NewGet returns a cobra.Command for getting Implementations from a Public Hub.
```

File: cmd/cli/cmd/policy/get.go [hunk 2]
```diff
@@ -9,6 +9,7 @@ import (
 	"github.com/spf13/cobra"
 )
 
+// NewGet return a cobra.Command for getting the Capact Global policy on a Capact environment
```
Comment (Trojan295) [inline cmd/cli/cmd/policy/get.go:12]:
```suggestion
// NewGet return a cobra.Command for getting the Capact Global policy on a Capact environment.
```

File: cmd/cli/cmd/policy/policy.go [hunk 3]
```diff
@@ -2,6 +2,7 @@ package policy
 
 import "github.com/spf13/cobra"
 
+// NewCmd returns a cobra.Command for the "policy" subcommand.
```
Comment (Trojan295) [inline cmd/cli/cmd/policy/policy.go:5]:
```suggestion
// NewCmd returns a cobra.Command for policy related operations.
```

File: cmd/cli/cmd/typeinstance/create.go [hunk 4]
```diff
@@ -23,6 +24,7 @@ type createOptions struct {
 	TypeInstancesFiles []string
 }
 
+// NewCreate returns a cobra.Command for create a TypeInstance on a Local Hub
```
Comment (Trojan295) [inline cmd/cli/cmd/typeinstance/create.go:27]:
```suggestion
// NewCreate returns a cobra.Command for creating a TypeInstance on a Local Hub.
```

File: pkg/argo-actions/update_type_instances.go [hunk 5]
```diff
@@ -12,19 +13,24 @@ import (
...
 
+// Update implements the Action interface.
+// It is used to update existing TypeInstances in the Local Hub.
 type Update struct {
 	log    *zap.Logger
 	client *local.Client
 	cfg    UpdateConfig
 }
 
+// NewUpdateAction returns a pointer to the Download struct, which is implementing the Action interface.
```
Comment (Trojan295) [inline pkg/argo-actions/update_type_instances.go:33]:
```suggestion
// NewUpdateAction returns a new Action instance for updating TypeInstances.
```

File: pkg/argo-actions/upload_type_instances.go [hunk 6]
```diff
@@ -12,19 +13,24 @@ import (
...
 
+// Upload implements the Action interface.
+// It is used to upload TypeInstances to the Local Hub.
 type Upload struct {
 	log    *zap.Logger
 	client *local.Client
 	cfg    UploadConfig
 }
 
+// NewUploadAction returns a pointer to the Upload struct, which is implementing the Action interface.
```
Comment (Trojan295) [inline pkg/argo-actions/upload_type_instances.go:33]:
```suggestion
// NewUploadAction returns Action instance to upload TypeInstances to Local Hub.
```

File: pkg/engine/api/graphql/json.go [hunk 7]
```diff
@@ -10,8 +10,10 @@ import (
 	"log"
 )
 
+// JSON represents a GraphQL scalar, which holds a JSON string.
 type JSON string
 
+// UnmarshalGQL unmarshals the GraphQL input to JSON
```
Comment (Trojan295) [inline pkg/engine/api/graphql/json.go:16]:
```suggestion
// UnmarshalGQL unmarshals the GraphQL input to JSON.
```

File: pkg/engine/api/graphql/policy.go [hunk 8]
```diff
@@ -2,11 +2,14 @@ package graphql
 
 // The types had to be moved out from generated models to add `omitempty` tags.
 
+// PolicyRule represents a single policy rule
```
Comment (Trojan295) [inline pkg/engine/api/graphql/policy.go:5]:
```suggestion
// PolicyRule represents a single policy rule.
```

File: pkg/engine/api/graphql/policy.go [hunk 9]
```diff
@@ -16,6 +19,7 @@ type PolicyRuleImplementationConstraints struct {
 	Path *string `json:"path,omitempty"`
 }
 
+// ManifestReferenceWithOptionalRevision is used to represent a Manifest Reference with an optional revision property
```
Comment (Trojan295) [inline pkg/engine/api/graphql/policy.go:22]:
```suggestion
// ManifestReferenceWithOptionalRevision is used to represent a Manifest Reference with an optional revision property.
```

File: pkg/engine/api/graphql/timestamp.go [hunk 10]
```diff
@@ -28,6 +30,7 @@ func (t *Timestamp) UnmarshalGQL(v interface{}) error {
 	return nil
 }
 
+// MarshalGQL writes the RFC3339 formated Timestamp to the provided writer.
```
Comment (Trojan295) [inline pkg/engine/api/graphql/timestamp.go:33]:
```suggestion
// MarshalGQL writes the RFC3339 formatted Timestamp to the provided writer.
```

File: pkg/engine/k8s/policy/types.go [hunk 11]
```diff
@@ -7,45 +7,63 @@ import (
 )
 
 const (
-	CurrentAPIVersion        = "0.2.0"
-	AnyInterfacePath  string = "cap.*"
+	// CurrentAPIVersion holds the current Policy API version
```
Comment (Trojan295) [inline pkg/engine/k8s/policy/types.go:10]:
```suggestion
	// CurrentAPIVersion holds the current Policy API version.
```

File: pkg/hub/client/policy_enforced_client.go [hunk 12]
```diff
@@ -90,6 +98,8 @@ func (e *PolicyEnforcedClient) ListTypeInstancesToInjectBasedOnPolicy(policyRule
 	return typeInstancesToInject
 }
 
+// ListAdditionalInputToInjectBasedOnPolicy returns additional input parameters,
+// which have to be injected into the Action, based on the current policies
```
Comment (Trojan295) [inline pkg/hub/client/policy_enforced_client.go:102]:
```suggestion
// which have to be injected into the Action, based on the current policies.
```

File: pkg/hub/client/public/options.go [hunk 13]
```diff
@@ -10,15 +11,17 @@ type ListImplementationRevisionsOptions struct {
 	sortByPathAscAndRevisionDesc bool
 }
 
+// Apply is used to configure the ListImplementationRevisionsOptions
```
Comment (Trojan295) [inline pkg/hub/client/public/options.go:14]:
```suggestion
// Apply is used to configure the ListImplementationRevisionsOptions.
```

File: pkg/runner/api.go [hunk 14]
```diff
@@ -6,25 +6,28 @@ import (
 	"fmt"
 )
 
-// API types used to ensure extendable function input/output.
 type (
+	// StartInput defines the input arguments to start a runner
```
Comment (Trojan295) [inline pkg/runner/api.go:10]:
```suggestion
	// StartInput defines the input arguments to start a runner.
```

File: pkg/runner/cloudsql/types.go [hunk 15]
```diff
@@ -10,31 +10,40 @@ import (
...
+// CommandType represents the operation type to be performed by the runner.
 type CommandType string
 
 const (
+	// CreateCommandType is an operation to create a new CloudSQL instance.
 	CreateCommandType = "create"
 )
 
 var (
+	// ErrInstanceCreateTimeout indicates the operation timed.
```
Comment (Trojan295) [inline pkg/runner/cloudsql/types.go:34]:
```suggestion
	// ErrInstanceCreateTimeout indicates the operation timed out.
```

File: pkg/runner/config.go [hunk 16]
```diff
@@ -40,10 +41,12 @@ type KubernetesPlatformConfig struct {
 // `json: cannot unmarshal string into Go struct field of type time.Duration`
 type Duration time.Duration
 
+// Duration returns the time.Duration representation
```
Comment (Trojan295) [inline pkg/runner/config.go:44]:
```suggestion
// Duration returns the time.Duration representation.
```

File: pkg/runner/helm/adapter.go [hunk 17]
```diff
@@ -37,14 +39,17 @@ func (r *runnerAdapter) Start(ctx context.Context, in runner.StartInput) (*runne
 	}, nil
 }
 
+// WaitForCompletion waits for the Helm runner operation to complete.
 func (r *runnerAdapter) WaitForCompletion(_ context.Context, _ runner.WaitForCompletionInput) (*runner.WaitForCompletionOutput, error) {
 	return r.out, nil
 }
 
+// Name returns the name of the Helm runner
```
Comment (Trojan295) [inline pkg/runner/helm/adapter.go:47]:
```suggestion
// Name returns the name of the Helm runner.
```

File: pkg/runner/terraform/types.go [hunk 18]
```diff
@@ -2,8 +2,19 @@ package terraform
 
 import "encoding/json"
 
+// CommandType represents the operation type to be performed by the runner.
 type CommandType string
 
+const (
+	// ApplyCommand is an operation to perform terraform apply
```
Comment (Trojan295) [inline pkg/runner/terraform/types.go:9]:
```suggestion
	// ApplyCommand is an operation to perform terraform apply.
```

File: pkg/runner/terraform/types.go [hunk 19]
```diff
@@ -2,8 +2,19 @@ package terraform
...
+	ApplyCommand = "apply"
+	// DestroyCommand is an operation to perform terraform destroy
```
Comment (Trojan295) [inline pkg/runner/terraform/types.go:11]:
```suggestion
	// DestroyCommand is an operation to perform terraform destroy.
```

File: pkg/runner/terraform/types.go [hunk 20]
```diff
@@ -2,8 +2,19 @@ package terraform
...
+	DestroyCommand = "destroy"
+	// PlanCommand is an operation to perform terraform plan
```
Comment (Trojan295) [inline pkg/runner/terraform/types.go:13]:
```suggestion
	// PlanCommand is an operation to perform terraform plan.
```

File: pkg/runner/terraform/types.go [hunk 21]
```diff
@@ -31,22 +44,26 @@ type Config struct {
...
 	TfstateFilePath          string `envconfig:"default=/tmp/terraform.tfstate"`
 }
 
+// Release stores the details about the Terraform release.
 type Release struct {
 	Name   string `json:"name"`
 	Source string `json:"source"`
 }
 
+// StateTypeInstance stores the details about the Terraform state TypeInstance
```
Comment (Trojan295) [inline pkg/runner/terraform/types.go:60]:
```suggestion
// StateTypeInstance stores the details about the Terraform state TypeInstance.
```

File: pkg/sdk/apis/0.0.1/types/types.extend.go [hunk 22]
```diff
@@ -1,4 +1,4 @@
-// Holds manually added types
+// Package types holds manually added types
```
Comment (Trojan295) [inline pkg/sdk/apis/0.0.1/types/types.extend.go:1]:
```suggestion
// Package types holds manually added types.
```

File: pkg/sdk/renderer/argo/options.go [hunk 23]
```diff
@@ -5,38 +5,47 @@ import (
...
+// WithPolicyOrder returns a RendererOption, which sets the priority order for the policy.
+// The priorty order is from the most important policy to the least important.
 func WithPolicyOrder(order policy.MergeOrder) RendererOption {
 	return func(r *dedicatedRenderer) {
 		r.policyEnforcedCli.SetPolicyOrder(order)
 	}
 }
 
+// WithOwnerID returns a RendererOption, which sets OwnerID for the workflow.
+// The OwnerID is used to lock the TypeInstances
```
Comment (Trojan295) [inline pkg/sdk/renderer/argo/options.go:48]:
```suggestion
// The OwnerID is used to lock the TypeInstances.
```

File: pkg/sdk/renderer/argo/types.go [hunk 24]
```diff
@@ -1,6 +1,7 @@
-// We had to copy the Argo Workflow Go struct as we need to extend the WorkflowStep syntax with our own keywords
 package argo
 
+// We had to copy the Argo Workflow Go struct as we need to extend the WorkflowStep syntax with our own keywords
```
Comment (Trojan295) [inline pkg/sdk/renderer/argo/types.go:3]:
```suggestion
// We had to copy the Argo Workflow Go struct as we need to extend the WorkflowStep syntax with our own keywords.
```

File: pkg/sdk/renderer/argo/types.go [hunk 25]
```diff
@@ -9,18 +10,23 @@ import (
 	wfv1 "github.com/argoproj/argo/v2/pkg/apis/workflow/v1alpha1"
 )
 
+// Workflow is the specification of a Workflow.
 type Workflow struct {
 	*wfv1.WorkflowSpec
 	Templates []*Template `json:"templates"`
 }
 
+// Template is a reusable and composable unit of execution in a workflow
```
Comment (Trojan295) [inline pkg/sdk/renderer/argo/types.go:19]:
```suggestion
// Template is a reusable and composable unit of execution in a workflow.
```

File: pkg/sdk/renderer/argo/types.go [hunk 26]
```diff
@@ -9,18 +10,23 @@ import (
...
 type Template struct {
 	*wfv1.Template
 	Steps []ParallelSteps `json:"steps,omitempty"`
 }
 
+// ParallelSteps define a series of sequential/parallel workflow steps
```
Comment (Trojan295) [inline pkg/sdk/renderer/argo/types.go:25]:
```suggestion
// ParallelSteps define a series of sequential/parallel workflow steps.
```

File: pkg/sdk/renderer/argo/types.go [hunk 27]
```diff
@@ -33,27 +39,35 @@ type WorkflowStep struct {
...
 
+// RunnerContextSecretRef hold a reference to the runner context
+// in a Kubernetes Secret resource.
 type RunnerContextSecretRef struct {
 	Name string
 	Key  string
 }
 
+// UserInputSecretRef hold a reference to the runner context
+// in a Kubernetes Secret resource
```
Comment (Trojan295) [inline pkg/sdk/renderer/argo/types.go:57]:
```suggestion
// in a Kubernetes Secret resource.
```

File: pkg/sdk/dbpopulator/loader.go [hunk 28]
```diff
@@ -33,14 +33,15 @@ func getManifestMetadata(yamlBytes []byte) (manifestMetadata, error) {
 	return mm, err
 }
 
+// Group return a map of the provided Manifests Paths, grouped by the Manifest Kind.
```
Comment (mszostok) [inline pkg/sdk/dbpopulator/loader.go:36]:
```suggestion
// Group returns a map of the provided Manifests Paths, grouped by the manifest kind.
```

File: pkg/sdk/manifest/validation.go [hunk 29]
```diff
@@ -13,14 +14,19 @@ import (
 	"sigs.k8s.io/yaml"
 )
 
+// Validator is a interface, with the ValidateFile method.
+// ValidateFile validates the Manifest in filepath and return a ValidationResult.
```
Comment (mszostok) [inline pkg/sdk/manifest/validation.go:18]:
```suggestion
// ValidateFile validates the manifest in filepath and return a ValidationResult.
```

File: pkg/sdk/manifest/validation.go [hunk 30]
```diff
@@ -13,14 +14,19 @@ import (
...
+// If other, not Manifest related errors occur, it will return an error.
```
Comment (mszostok) [inline pkg/sdk/manifest/validation.go:19]:
```suggestion
// If other, not manifest related errors occur, it will return an error.
```

File: pkg/sdk/manifest/validation.go [hunk 31]
```diff
@@ -13,14 +14,19 @@ import (
...
 type Validator interface {
 	ValidateFile(filepath string) (ValidationResult, error)
 }
 
+// ValidationResult hold the result of the Manifest validation.
```
Comment (mszostok) [inline pkg/sdk/manifest/validation.go:24]:
```suggestion
// ValidationResult hold the result of the manifest validation.
```

File: pkg/sdk/manifest/validation.go [hunk 32]
```diff
@@ -13,14 +14,19 @@ import (
...
 type ValidationResult struct {
 	Errors []error
 }
 
+// Valid returns true, if the Manifest contains no errors.
```
Comment (mszostok) [inline pkg/sdk/manifest/validation.go:29]:
```suggestion
// Valid returns true, if the manifest contains no errors.
```

File: pkg/sdk/manifest/validation.go [hunk 33]
```diff
@@ -31,6 +37,7 @@ func newValidationResult(errors ...error) ValidationResult {
 	}
 }
 
+// FilesystemManifestValidator validates Manifests using a OCF specification, which is read from a filesystem.
```
Comment (mszostok) [inline pkg/sdk/manifest/validation.go:40]:
```suggestion
// FilesystemManifestValidator validates manifests using a OCF specification, which is read from a filesystem.
```

File: pkg/sdk/manifest/validation.go [hunk 34]
```diff
@@ -54,8 +62,9 @@ func NewFilesystemValidator(fs http.FileSystem, schemaRootPath string) Validator
 	}
 }
 
-func (v *FilesystemManifestValidator) ValidateFile(filepath string) (ValidationResult, error) {
-	data, err := ioutil.ReadFile(filepath)
+// ValidateFile validates a Manifest.
```
Comment (mszostok) [inline pkg/sdk/manifest/validation.go:65]:
```suggestion
// ValidateFile validates a manifest.
```

**Review by mszostok — APPROVED** [review]
